// lib/spotifyAuth.ts
//
// Authorising SongRank to write playlists on somebody's Spotify account, and
// keeping the tokens that let it.
//
// ## Why this is NOT an Auth.js provider
//
// auth.ts is Google-only, JWT session strategy, no database adapter, and that
// combination is deliberate (see its own comments). Adding Spotify as a linked
// provider means adding an adapter, which means moving sessions into the
// database, which means touching the one flow that must never break. The cost
// would be paid by every signed-in user to give some of them a playlist.
//
// Spotify here is a CAPABILITY, not an identity: nobody signs in with it,
// nobody's account is it. "This user has authorised us to write playlists" is
// a fact about a Google-identified user, so it lives in its own table keyed by
// our own user id, and this module is an ordinary OAuth client rather than
// part of the sign-in path. Disconnecting is then just deleting a row, with no
// question about what happens to the session.
//
// ## Refresh tokens are long-lived credentials
//
// A Spotify refresh token does not expire. Anyone holding one can mint access
// tokens and write to that account's playlists indefinitely, so a database
// dump is a credential leak unless the tokens in it are useless on their own.
// Neon encrypts at rest, which protects the disk but not a dump, a backup
// copied somewhere careless, or a SELECT by anything that gets query access.
// So tokens are encrypted here as well, with a key derived from AUTH_SECRET --
// which lives in Vercel's environment and is not in the database. Compromising
// either alone gets you nothing.

import { createCipheriv, createDecipheriv, randomBytes, scryptSync, timingSafeEqual } from "node:crypto";

const ACCOUNTS_BASE = "https://accounts.spotify.com";

/**
 * What we ask for, and nothing else.
 *
 * Both playlist scopes because a playlist is created as one or the other and
 * the person choosing should not be forced public to use the feature. No
 * read scopes, no library scopes, no listening history: this feature writes a
 * playlist, so it asks to write playlists. An authorisation screen listing
 * permissions a feature does not need is how people learn not to read them.
 */
export const SCOPES = ["playlist-modify-public", "playlist-modify-private"] as const;

export function hasSpotifyCredentials(): boolean {
    return Boolean(process.env.SPOTIFY_CLIENT_ID && process.env.SPOTIFY_CLIENT_SECRET);
}

/** Where Spotify sends the browser back. Must match a URI registered on the
 * app exactly, including scheme and any trailing slash. */
export function redirectUri(origin: string): string {
    return `${new URL(origin).origin}/api/spotify/callback`;
}

/**
 * The URL to send someone to in order to authorise.
 *
 * `state` is the CSRF defence and is not optional: without it, a third party
 * can hand somebody a crafted callback link and attach THEIR Spotify account
 * to the victim's SongRank account -- after which every playlist the victim
 * exports is written somewhere they cannot see. The caller mints it, puts it
 * in an httpOnly cookie, and compares on the way back (see `statesMatch`).
 */
export function authorizeUrl(origin: string, state: string): string {
    const params = new URLSearchParams({
        client_id: process.env.SPOTIFY_CLIENT_ID ?? "",
        response_type: "code",
        redirect_uri: redirectUri(origin),
        scope: SCOPES.join(" "),
        state,
        // Spotify remembers a previous approval and will bounce straight
        // through without showing anything. That is fine for re-authorising,
        // but it also means a person cannot tell whether anything happened,
        // so the dialogue is forced -- the same reasoning as
        // `prompt: "select_account"` on the Google provider in auth.ts.
        show_dialog: "true",
    });
    return `${ACCOUNTS_BASE}/authorize?${params.toString()}`;
}

/** Constant-time comparison of the state we issued against the one returned. */
export function statesMatch(issued: string | undefined, returned: string | undefined): boolean {
    if (!issued || !returned) return false;
    const a = Buffer.from(issued);
    const b = Buffer.from(returned);
    // timingSafeEqual throws on a length mismatch rather than returning false,
    // and the lengths themselves are not secret.
    if (a.length !== b.length) return false;
    return timingSafeEqual(a, b);
}

// --- token encryption ------------------------------------------------------

const ALGORITHM = "aes-256-gcm";
/** Fixed salt: the secret being stretched is already high-entropy (AUTH_SECRET
 * is generated by `npx auth secret`), so the salt is here to domain-separate
 * this key from any other use of that secret, not to resist a dictionary
 * attack on a human-chosen password. */
const KEY_SALT = "songrank:spotify:v1";

function key(): Buffer {
    const secret = process.env.AUTH_SECRET;
    if (!secret) throw new Error("AUTH_SECRET is required to store Spotify tokens");
    return scryptSync(secret, KEY_SALT, 32);
}

/**
 * Encrypts a token for storage. Output is `iv.authTag.ciphertext`, base64url.
 *
 * GCM rather than CBC so the ciphertext is authenticated: a token altered in
 * the database fails to decrypt instead of decrypting to something else that
 * then gets sent to Spotify as a bearer credential. The IV is random per call,
 * so storing the same token twice produces different ciphertext and the column
 * cannot be used to tell whether two rows hold the same value.
 */
export function encryptToken(plaintext: string): string {
    const iv = randomBytes(12);
    const cipher = createCipheriv(ALGORITHM, key(), iv);
    const encrypted = Buffer.concat([cipher.update(plaintext, "utf8"), cipher.final()]);
    return [iv, cipher.getAuthTag(), encrypted].map((b) => b.toString("base64url")).join(".");
}

/**
 * Reverses `encryptToken`, or returns null.
 *
 * Null rather than throwing, for anything malformed, tampered with, or
 * encrypted under a different AUTH_SECRET. A rotated secret is the realistic
 * case, and it should mean "this person needs to reconnect Spotify" -- an
 * ordinary, recoverable state -- rather than a 500 on a page that merely
 * wanted to know whether to show a button.
 */
export function decryptToken(stored: string): string | null {
    try {
        const [ivPart, tagPart, dataPart] = stored.split(".");
        // `dataPart` is checked for PRESENCE, not truthiness. Encrypting an
        // empty string yields an empty payload, so `iv.tag.` is a well-formed
        // sealed value and rejecting it broke the round-trip property that
        // everything else here assumes. Caught by the verify suite rather than
        // in production, where it would have meant a token that stored fine
        // and read back as "not connected".
        if (!ivPart || !tagPart || dataPart === undefined) return null;
        const decipher = createDecipheriv(ALGORITHM, key(), Buffer.from(ivPart, "base64url"));
        decipher.setAuthTag(Buffer.from(tagPart, "base64url"));
        return Buffer.concat([
            decipher.update(Buffer.from(dataPart, "base64url")),
            decipher.final(),
        ]).toString("utf8");
    } catch {
        return null;
    }
}

// --- expiry ----------------------------------------------------------------

/**
 * Refresh this many milliseconds BEFORE the token actually expires.
 *
 * Exporting a long ranking is many sequential requests, and a token that was
 * valid when the export started can expire partway through it. Treating the
 * last minute of a token's life as already expired costs one extra refresh and
 * removes a failure that would otherwise strike halfway through writing
 * somebody's playlist -- the worst possible moment, because the playlist
 * already exists and is half full.
 */
export const EXPIRY_MARGIN_MS = 60_000;

export function isExpired(expiresAt: Date | string, now = new Date()): boolean {
    const at = typeof expiresAt === "string" ? Date.parse(expiresAt) : expiresAt.getTime();
    if (!Number.isFinite(at)) return true;
    return at - EXPIRY_MARGIN_MS <= now.getTime();
}

/** When a token issued now, lasting `expiresInSeconds`, actually expires. */
export function expiryFrom(expiresInSeconds: number, now = new Date()): Date {
    const seconds = Number.isFinite(expiresInSeconds) && expiresInSeconds > 0 ? expiresInSeconds : 3600;
    return new Date(now.getTime() + seconds * 1000);
}

// --- the thin HTTP half ----------------------------------------------------

export interface TokenSet {
    accessToken: string;
    /** Absent on a refresh: Spotify only returns a new one sometimes, and the
     * old one stays valid when it doesn't. Callers must keep the existing one
     * rather than overwriting it with undefined. */
    refreshToken?: string;
    expiresAt: Date;
}

interface RawTokenResponse {
    access_token?: string;
    refresh_token?: string;
    expires_in?: number;
}

/** Client credentials as Spotify's token endpoint wants them: HTTP Basic. */
function basicAuth(): string {
    const pair = `${process.env.SPOTIFY_CLIENT_ID}:${process.env.SPOTIFY_CLIENT_SECRET}`;
    return `Basic ${Buffer.from(pair).toString("base64")}`;
}

async function tokenRequest(body: URLSearchParams): Promise<TokenSet | null> {
    try {
        const res = await fetch(`${ACCOUNTS_BASE}/api/token`, {
            method: "POST",
            headers: {
                Authorization: basicAuth(),
                "Content-Type": "application/x-www-form-urlencoded",
            },
            body,
            signal: AbortSignal.timeout(10_000),
        });
        if (!res.ok) {
            // Logged, not surfaced: the body can contain the client secret's
            // error context, and the caller only needs "this didn't work".
            console.error("SPOTIFY TOKEN ERROR:", res.status, await res.text().catch(() => ""));
            return null;
        }
        const data = (await res.json()) as RawTokenResponse;
        if (!data.access_token) return null;
        return {
            accessToken: data.access_token,
            refreshToken: data.refresh_token,
            expiresAt: expiryFrom(data.expires_in ?? 3600),
        };
    } catch (err) {
        console.error("SPOTIFY TOKEN ERROR:", err);
        return null;
    }
}

/** Exchanges the `code` from the callback for a token set. */
export function exchangeCode(code: string, origin: string): Promise<TokenSet | null> {
    return tokenRequest(
        new URLSearchParams({
            grant_type: "authorization_code",
            code,
            redirect_uri: redirectUri(origin),
        })
    );
}

/** Trades a refresh token for a fresh access token. */
export function refreshAccessToken(refreshToken: string): Promise<TokenSet | null> {
    return tokenRequest(new URLSearchParams({ grant_type: "refresh_token", refresh_token: refreshToken }));
}

/** The authorised account's own Spotify user id, needed to create a playlist. */
export async function currentUserId(accessToken: string): Promise<string | null> {
    try {
        const res = await fetch("https://api.spotify.com/v1/me", {
            headers: { Authorization: `Bearer ${accessToken}` },
            signal: AbortSignal.timeout(10_000),
        });
        if (!res.ok) return null;
        const data = (await res.json()) as { id?: string };
        return data.id ?? null;
    } catch {
        return null;
    }
}
